/** Fields requested from Sentry Discover / Events API for session investigation. */
export const SENTRY_DISCOVER_FIELDS = [
  "id",
  "timestamp",
  "title",
  "message",
  "transaction",
  "user.id",
  "user.email",
  "session.id",
  "contexts.trace.trace_id",
  "tags[type]",
  "tags[status]",
  "tags[action_type]",
  "tags[session]",
  "tags[user_id]",
  "tags[service]",
  "tags[method]",
  "tags[endpoint]",
  "tags[http_status]",
  "tags[session_id]",
  "tags[action_index]",
  "tags[order_id]",
  "tags[failure_reason]",
  "tags[role]",
  "tags[account_type]",
  "project.name",
] as const;
